name: gnn_model_stealing
channels:
  - pytorch
  - dglteam
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=1.13
  - torchvision=0.14
  - torchaudio=0.13
  - cpuonly
  - dgl=0.9.1
  - numpy<2
  - scipy
  - scikit-learn
  - pandas
  - matplotlib
  - networkx
  - tqdm
  - pyyaml
  - yacs
  - setuptools<70
  - ipython
  - pip:
      - tabulate==0.9.0
