name: gnn_model_stealing
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - numpy<2
  - scipy
  - scikit-learn
  - pandas
  - matplotlib
  - networkx
  - tqdm
  - pyyaml
  - yacs
  - setuptools<70
  - ipython

  - pytorch=2.1.2
  - torchvision=0.16.2
  - torchaudio=2.1.2
  - pytorch-cuda=11.8

  - pip:
      - --find-links https://data.pyg.org/whl/torch-2.1.2+cu118.html
#      - pyg_lib
      - torch_scatter
      - torch_sparse
      - torch_cluster
      - torch_spline_conv
      - torch-geometric==2.5.3
      - tabulate==0.9.0
