name: gnn_model_stealing
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=1.13
  - torchvision=0.14
  - torchaudio=0.13
  - cpuonly
  - numpy<2
  - scipy
  - scikit-learn
  - pandas
  - matplotlib
  - networkx
  - tqdm
  - pyyaml
  - yacs
  - setuptools<70
  - ipython
  - pip:
      - tabulate==0.9.0
      - torch-geometric==2.3.1
      - torch-scatter; platform_system == "Windows" and python_version == "3.10"
      - torch-sparse; platform_system == "Windows" and python_version == "3.10"
      - torch-cluster; platform_system == "Windows" and python_version == "3.10"
      - torch-spline-conv; platform_system == "Windows" and python_version == "3.10"
      - -f https://data.pyg.org/whl/torch-1.13.0+cpu.html
